config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
 # devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root "homes#index"

devise_for :users, controllers: { sessions: 'users/sessions' }

resources :restaurants do
	member do
		get :delete
	end
end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

has_many :restaurants
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  #before_action :authenticate_user! 

  rescue_from Pundit::NotAuthorizedError do 
  redirect_to restaurants_path, alert:'You do not have access to this page'
  	
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

	def index
		@restaurants = Restaurant.all
		#@restaurants.order(:updated_at)
	end
	
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  
  before_action :authenticate_user!, except: [:index, :show]
  #before_action :set_restaurant, only: [:edit, :update, :destroy]
  after_action :verify_authorized, except: [:index, :show] 
  #after_action :verify_policy_scoped, only: :index

  def index
   # @restaurants = policy_scope(Restaurant).reverse
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = current_user.restaurants.new
    authorize @restaurant
    #authorize @user
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def create
    @restaurant = current_user.restaurants.create(restaurant_params)
    authorize @restaurant
     #authorize @user
    flash[:notice] = "Restaurant Added Successfully"
    if @restaurant.save
      redirect_to(restaurants_path)
    else 
      render('new')
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
    authorize @restaurant
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    authorize @restaurant
    if @restaurant.update_attributes(restaurant_params)

    flash[:notice] = "Restaurant Updated Successfully"
    #redirect_to(pages_path)
    redirect_to(restaurants_path(@restaurant))
    else
      render('edit')
    end
  end


  def delete
    @restaurant = Restaurant.find(params[:id])
    authorize @restaurant
    @restaurant.destroy
    flash[:notice] = "Restaurant Deleted Successfully"
    redirect_to(restaurants_path)

  end

  private
  def set_restaurant
    @resturant = Restaurant.find(params[:id])
    authorize @restaurant
  end

  def restaurant_params
  params.require(:restaurant).permit(:name, :location, :cuisine, :service_charge, :vat, :contact)

  end



end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/views/homes/index.html.erb
<! DOCTYPE html>
<html>

<div class="container">
	<div class="row">
		<div class="col-sm">
	<head>
	<title>"Foodmandu" %></title>
	<h1>Foodmandu</h1>
	</head>
	</div>
</div>

<div class="container">
	<%= link_to(image_tag("foodmandu.jpg", width: '800px', height: '400px'), 'https://www.facebook.com' )%>
</div>

<div class="container">
	<div class="row">
		<div class="col-sm-4">
			<h3>Recently Added Member</h3>

			<p> </p>
		</div>


		<div class="col-sm-4">
			<h3> asdasd</h3>
	
		</div>

		<div class="col-sm-4">
		</div>
	</div>
		<div class="container">
	  <div class="row">
	  	<div class="col-sm-12">
				

				<% @restaurants.each do |r| %>
			    <div class="col-sm-4">
			    <div class="col-sm-4">
			     <%= link_to(image_tag("bota.jpg", width: '100px', height: '100px'), restaurant_path(r)) %>
			     </div>
			     <div class="col-sm-3">
			      <a><%= link_to("#{r.name}", restaurant_path(r), :class => 'action show') %></a>
			      <a><%= "#{r.location}" %></a>
			      <a><%= "#{r.cuisine}" %></a>
			      <a><%= link_to("Show", restaurant_path(r), :class => 'action show') %></a>
				<a><%= link_to("Edit", edit_restaurant_path(r), :class => 'action edit') if policy(r).update? %></a>
				<a><%= link_to("Delete", delete_restaurant_path(r), :class => 'action delete') if policy(r).delete?  %></a>
				</div>
			    </div>
				<% end %>
		   </div>
	  </div>

	  
	  	

	  
	</div>
</div>
		




	
</div>

<!-- before yield -->

<!-- after yield -->

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Foodmandu" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>


    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" <%= link_to "Foodmandu", root_path %></a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Login", user_session_path  %></li>
            <li><%= link_to "Register", new_user_registration_path  %></li>
            <li><%= link_to 'Logout', destroy_user_session_path %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Find Restaurants", restaurants_path  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Ashesh 2017</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/restaurants/_form.html.erb
<table summary="restaurant form fields">
	<tr>
		<th>Name</th>
		<td><%= f.text_field(:name) %> </td>
	</tr>
	<tr>
        <th> Location</th>
        <td><%= f.text_field(:location) %></td>
      </tr>
	<tr>
		<th>Cuisine</th>
		<td><%= f.text_field(:cuisine) %> </td>
	</tr>
	<tr>
		<th>Service Charge</th>
		<td><%= f.text_field(:service_charge) %> </td>
	</tr>
	<tr>
		<th>Vat</th>
		<td><%= f.text_field(:vat) %> </td>
	</tr>
	<tr>
		<th>Contact</th>
		<td><%= f.text_field(:contact) %> </td>
	</tr>


</table>

app/views/restaurants/create.html.erb
<h1>Restaurant#create</h1>
<p>Find me in app/views/restaurant/create.html.erb</p>

app/views/restaurants/delete.html.erb
<h1>Restaurant#delete</h1>
<p>Find me in app/views/restaurant/delete.html.erb</p>

app/views/restaurants/edit.html.erb
<!-- <h1>Subjects#edit</h1>
<p>Find me in app/views/subjects/edit.html.erb</p>
 -->
 <%= link_to('<< Back to List', restaurants_path, :class => 'back-link') %>

 <div class="Restaurant edit">
 	<h2>Update Restaurant</h2>

<%= form_for(@restaurant) do |f| %>

<%= render(:partial => 'form', :locals => {:f => f}) %>

</table>

<div class="form button">
	<%= f.submit("Update Restaurant") %>
</div>

	 <% end%>
</div>

app/views/restaurants/index.html.erb
<! DOCTYPE html>
<html>

<div class="container">
	<head>
	<title>"Restaurant" %></title>
	<h3>Member Restaurant</h3>
	<p>Find restaurants of your choice from the list below and click 'Place Order' to continue.</p>
	<a><%= link_to("Add New Restaurant", new_restaurant_path, :class => 'action new') %></a>
	</head>
</div>

<!-- <div class="table-responsive">
<table class="table">
<thead>
	<tr>
		<th>SN</th>
		<th>Name</th>
		<th>location</th>
		<th>cuisine</th>
		<th>service charge</th>
		<th>Vat</th>
		<th>contact</th>
	</tr>
</thead>
<tbody>
	<% @restaurants.each do |r| %>
	<tr>
		<td><%= r.id %></td>
		<td><%= r.name %></td>
		<td><%= r.location %> </td>
		<td><%= r.cuisine %> </td>
		<td><%= r.service_charge %></td>
		<td><%= r.vat %></td>
		<td><%= r.contact %></td>
	</tr>
	<% end%>

	</tbody>

</table>
</div>
 -->
	<div class="container">
	  <div class="row">
	  	<div class="col-sm-9">
				<% @restaurants.each do |r| %>
			    <div class="col-sm-3">
			      <h3><%= link_to("#{r.name}", restaurant_path(r), :class => 'action show') %></h3>
			      <p><%= "located in #{r.location}" %></p>
			      <a><%= "cuisine: #{r.cuisine}" %></a>
			      <a><%= link_to("Show", restaurant_path(r), :class => 'action show') %></a>
				<a><%= link_to("Edit", edit_restaurant_path(r), :class => 'action edit') if policy(r).update? %></a>
				<a><%= link_to("Delete", delete_restaurant_path(r), :class => 'action delete') if policy(r).delete?  %></a>
			    </div>
				<% end %>
		   </div>
	  </div>

	  
	  	

	  
	</div>

<!-- </div>

<div class="container">
	<div class="row">
		<div class="col-sm-4">
			<h3></h3>
			<p> </p>
		</div>

		<div class="col-sm-4">
		</div>
	</div>
</div> -->

		
<!-- before yield -->

<!-- after yield -->

</html>

app/views/restaurants/new.html.erb
<%= link_to('<< Back to List', restaurants_path, :class => 'back-link') %>

 <div class="restaurant new">
 	<h2>Add A New Restaurant</h2>

<%= form_for(@restaurant) do |f| %>

<%= render(:partial => 'form', :locals => {:f => f}) %>

<div class="form button">
	<%= f.submit("Add Restaurant") %>
</div>

	 <% end%>
</div>
 

app/views/restaurants/show.html.erb
<div class="container">
<%= link_to("<< Back to List", restaurants_path, :class => 'back-list') %>
<h2><%= @restaurant.name%> </h2>
<p><%= "This restaurant is located in #{@restaurant.location} "%></p>

</div>